### ISSUE TITLE
MVP Roadmap

### ISSUE THREAD

**Issue by k11q** [farhan-helmy/uploadje#2]
# MVP Roadmap
Description

## General
- [ ] #11

## Backend
- [ ] #3
- [x] #5
- [ ] #7
- [x] #12
- [ ] #13
- [ ] feat: CRUD api key - enable add and delete secret keys
- [ ] enhance: add prefix to app_id and secret_key 
- [ ] feat: create `/internal` routes for returning frontend specific data
- [ ] feat(images): return get all images with pagination
- [ ] feat(auth): registration confirmation email

### Planned
- [ ] dev: add eslint
- [ ] feat(billings): create billings and subscription flow

## Frontend
- [x] feat: register page
- [x] feat: login page
- [ ] feat: reset password page
- [x] feat: apps page
- [ ] feat: images page
- [ ] feat: settings page
- [ ] feat: api key page
- [ ] feat: overview page
- [ ] feat: profile page

### Planned
- [ ] feat: billings page
